# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Leon\Desktop\Robustar_implementation\launcher\resources\launcher_v2.ui',
# licensing of 'C:\Users\Leon\Desktop\Robustar_implementation\launcher\resources\launcher_v2.ui' applies.
#
# Created: Sun Jul  3 16:41:16 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RobustarLauncher(object):
    def setupUi(self, RobustarLauncher):
        RobustarLauncher.setObjectName("RobustarLauncher")
        RobustarLauncher.resize(1000, 850)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        RobustarLauncher.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../doc/logo_short.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RobustarLauncher.setWindowIcon(icon)
        RobustarLauncher.setStyleSheet("QWidget{font: 8pt \"Arial\"}\n"
"QPushButton{background-color: #E1E1E1; \n"
"            font: 8pt Arial;\n"
"            border: 1px solid #ADADAD;}\n"
"QPushButton:hover {\n"
"   background-color: #E3ECF3;\n"
"   border: 1px solid #3287CA;\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(RobustarLauncher)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1001, 841))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.header = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setMaximumSize(QtCore.QSize(164, 42))
        self.header.setText("")
        self.header.setTextFormat(QtCore.Qt.AutoText)
        self.header.setPixmap(QtGui.QPixmap("../doc/logo_long.png"))
        self.header.setScaledContents(True)
        self.header.setIndent(-1)
        self.header.setObjectName("header")
        self.headerLayout.addWidget(self.header)
        self.verticalLayout.addLayout(self.headerLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(15, -1, 11, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonFrame = QtWidgets.QFrame(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.buttonFrame.setFont(font)
        self.buttonFrame.setStyleSheet("#buttonFrame{background: #F9F9F9}\n"
"")
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.layoutWidget1 = QtWidgets.QWidget(self.buttonFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 161, 771))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.buttonLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.buttonLayout.setSpacing(60)
        self.buttonLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttonLayout.setContentsMargins(-1, 60, -1, -1)
        self.buttonLayout.setObjectName("buttonLayout")
        self.loadButtonLayout = QtWidgets.QHBoxLayout()
        self.loadButtonLayout.setContentsMargins(-1, 0, -1, -1)
        self.loadButtonLayout.setObjectName("loadButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loadButtonLayout.addItem(spacerItem)
        self.loadProfileButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadProfileButton.sizePolicy().hasHeightForWidth())
        self.loadProfileButton.setSizePolicy(sizePolicy)
        self.loadProfileButton.setMinimumSize(QtCore.QSize(100, 25))
        self.loadProfileButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.loadProfileButton.setFont(font)
        self.loadProfileButton.setStyleSheet("")
        self.loadProfileButton.setObjectName("loadProfileButton")
        self.loadButtonLayout.addWidget(self.loadProfileButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loadButtonLayout.addItem(spacerItem1)
        self.buttonLayout.addLayout(self.loadButtonLayout)
        self.saveButtonLayout = QtWidgets.QHBoxLayout()
        self.saveButtonLayout.setObjectName("saveButtonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveButtonLayout.addItem(spacerItem2)
        self.saveProfileButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveProfileButton.sizePolicy().hasHeightForWidth())
        self.saveProfileButton.setSizePolicy(sizePolicy)
        self.saveProfileButton.setMinimumSize(QtCore.QSize(100, 25))
        self.saveProfileButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.saveProfileButton.setFont(font)
        self.saveProfileButton.setObjectName("saveProfileButton")
        self.saveButtonLayout.addWidget(self.saveProfileButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveButtonLayout.addItem(spacerItem3)
        self.buttonLayout.addLayout(self.saveButtonLayout)
        self.startButtonLayout = QtWidgets.QHBoxLayout()
        self.startButtonLayout.setObjectName("startButtonLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startButtonLayout.addItem(spacerItem4)
        self.startServerButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startServerButton.sizePolicy().hasHeightForWidth())
        self.startServerButton.setSizePolicy(sizePolicy)
        self.startServerButton.setMinimumSize(QtCore.QSize(100, 25))
        self.startServerButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.startServerButton.setFont(font)
        self.startServerButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startServerButton.setObjectName("startServerButton")
        self.startButtonLayout.addWidget(self.startServerButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.startButtonLayout.addItem(spacerItem5)
        self.buttonLayout.addLayout(self.startButtonLayout)
        self.stopButtoLayout = QtWidgets.QHBoxLayout()
        self.stopButtoLayout.setObjectName("stopButtoLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stopButtoLayout.addItem(spacerItem6)
        self.stopServerButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopServerButton.sizePolicy().hasHeightForWidth())
        self.stopServerButton.setSizePolicy(sizePolicy)
        self.stopServerButton.setMinimumSize(QtCore.QSize(100, 25))
        self.stopServerButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.stopServerButton.setFont(font)
        self.stopServerButton.setObjectName("stopServerButton")
        self.stopButtoLayout.addWidget(self.stopServerButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.stopButtoLayout.addItem(spacerItem7)
        self.buttonLayout.addLayout(self.stopButtoLayout)
        self.deleteButtonLayout = QtWidgets.QHBoxLayout()
        self.deleteButtonLayout.setObjectName("deleteButtonLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deleteButtonLayout.addItem(spacerItem8)
        self.deleteServerButton = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteServerButton.sizePolicy().hasHeightForWidth())
        self.deleteServerButton.setSizePolicy(sizePolicy)
        self.deleteServerButton.setMinimumSize(QtCore.QSize(100, 25))
        self.deleteServerButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.deleteServerButton.setFont(font)
        self.deleteServerButton.setObjectName("deleteServerButton")
        self.deleteButtonLayout.addWidget(self.deleteServerButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.deleteButtonLayout.addItem(spacerItem9)
        self.buttonLayout.addLayout(self.deleteButtonLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.buttonLayout.addItem(spacerItem10)
        self.buttonLayout.setStretch(0, 1)
        self.buttonLayout.setStretch(1, 1)
        self.buttonLayout.setStretch(2, 1)
        self.buttonLayout.setStretch(3, 1)
        self.buttonLayout.setStretch(4, 1)
        self.buttonLayout.setStretch(5, 2)
        self.horizontalLayout_2.addWidget(self.buttonFrame)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.createTab = QtWidgets.QWidget()
        self.createTab.setObjectName("createTab")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.createTab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(20, 10, 771, 411))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dockerGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.dockerGroupBox.setFont(font)
        self.dockerGroupBox.setObjectName("dockerGroupBox")
        self.layoutWidget2 = QtWidgets.QWidget(self.dockerGroupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 361, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.nameInput = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameInput.sizePolicy().hasHeightForWidth())
        self.nameInput.setSizePolicy(sizePolicy)
        self.nameInput.setMinimumSize(QtCore.QSize(0, 20))
        self.nameInput.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.nameInput.setFont(font)
        self.nameInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameInput.setClearButtonEnabled(True)
        self.nameInput.setObjectName("nameInput")
        self.horizontalLayout_8.addWidget(self.nameInput)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.versionComboBox = QtWidgets.QComboBox(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.versionComboBox.sizePolicy().hasHeightForWidth())
        self.versionComboBox.setSizePolicy(sizePolicy)
        self.versionComboBox.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.versionComboBox.setFont(font)
        # self.versionComboBox.setPlaceholderText("")
        self.versionComboBox.setObjectName("vesrsionComboBox")
        self.versionComboBox.addItem("")
        self.versionComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.versionComboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.dockerGroupBox)
        self.portGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.portGroupBox.setFont(font)
        self.portGroupBox.setObjectName("portGroupBox")
        self.layoutWidget3 = QtWidgets.QWidget(self.portGroupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 361, 211))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.websitePortInput = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.websitePortInput.sizePolicy().hasHeightForWidth())
        self.websitePortInput.setSizePolicy(sizePolicy)
        self.websitePortInput.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.websitePortInput.setFont(font)
        self.websitePortInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.websitePortInput.setClearButtonEnabled(True)
        self.websitePortInput.setObjectName("websitePortInput")
        self.horizontalLayout_9.addWidget(self.websitePortInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.backendPortInput = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backendPortInput.sizePolicy().hasHeightForWidth())
        self.backendPortInput.setSizePolicy(sizePolicy)
        self.backendPortInput.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.backendPortInput.setFont(font)
        self.backendPortInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.backendPortInput.setClearButtonEnabled(True)
        self.backendPortInput.setObjectName("backendPortInput")
        self.horizontalLayout_12.addWidget(self.backendPortInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.tensorboardPortInput = QtWidgets.QLineEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tensorboardPortInput.sizePolicy().hasHeightForWidth())
        self.tensorboardPortInput.setSizePolicy(sizePolicy)
        self.tensorboardPortInput.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.tensorboardPortInput.setFont(font)
        self.tensorboardPortInput.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tensorboardPortInput.setClearButtonEnabled(True)
        self.tensorboardPortInput.setObjectName("tensorboardPortInput")
        self.horizontalLayout_13.addWidget(self.tensorboardPortInput)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addWidget(self.portGroupBox)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pathGroupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.pathGroupBox.setFont(font)
        self.pathGroupBox.setObjectName("pathGroupBox")
        self.layoutWidget4 = QtWidgets.QWidget(self.pathGroupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 361, 371))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.trainPathDisplay = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainPathDisplay.sizePolicy().hasHeightForWidth())
        self.trainPathDisplay.setSizePolicy(sizePolicy)
        self.trainPathDisplay.setMinimumSize(QtCore.QSize(175, 0))
        self.trainPathDisplay.setMaximumSize(QtCore.QSize(104, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.trainPathDisplay.setFont(font)
        self.trainPathDisplay.setMouseTracking(True)
        self.trainPathDisplay.setText("")
        self.trainPathDisplay.setReadOnly(False)
        self.trainPathDisplay.setObjectName("trainPathDisplay")
        self.horizontalLayout_16.addWidget(self.trainPathDisplay)
        self.trainPathButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trainPathButton.sizePolicy().hasHeightForWidth())
        self.trainPathButton.setSizePolicy(sizePolicy)
        self.trainPathButton.setMinimumSize(QtCore.QSize(28, 0))
        self.trainPathButton.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.trainPathButton.setFont(font)
        self.trainPathButton.setObjectName("trainPathButton")
        self.horizontalLayout_16.addWidget(self.trainPathButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.testPathDisplay = QtWidgets.QLineEdit(self.layoutWidget4)
        self.testPathDisplay.setMinimumSize(QtCore.QSize(175, 0))
        self.testPathDisplay.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.testPathDisplay.setFont(font)
        self.testPathDisplay.setText("")
        self.testPathDisplay.setObjectName("testPathDisplay")
        self.horizontalLayout_17.addWidget(self.testPathDisplay)
        self.testPathButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testPathButton.sizePolicy().hasHeightForWidth())
        self.testPathButton.setSizePolicy(sizePolicy)
        self.testPathButton.setMinimumSize(QtCore.QSize(28, 0))
        self.testPathButton.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.testPathButton.setFont(font)
        self.testPathButton.setObjectName("testPathButton")
        self.horizontalLayout_17.addWidget(self.testPathButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.checkPointPathDisplay = QtWidgets.QLineEdit(self.layoutWidget4)
        self.checkPointPathDisplay.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.checkPointPathDisplay.setFont(font)
        self.checkPointPathDisplay.setText("")
        self.checkPointPathDisplay.setObjectName("checkPointPathDisplay")
        self.horizontalLayout_18.addWidget(self.checkPointPathDisplay)
        self.checkPointPathButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkPointPathButton.sizePolicy().hasHeightForWidth())
        self.checkPointPathButton.setSizePolicy(sizePolicy)
        self.checkPointPathButton.setMinimumSize(QtCore.QSize(28, 0))
        self.checkPointPathButton.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.checkPointPathButton.setFont(font)
        self.checkPointPathButton.setObjectName("checkPointPathButton")
        self.horizontalLayout_18.addWidget(self.checkPointPathButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_15.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.influencePathDisplay = QtWidgets.QLineEdit(self.layoutWidget4)
        self.influencePathDisplay.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.influencePathDisplay.setFont(font)
        self.influencePathDisplay.setText("")
        self.influencePathDisplay.setObjectName("influencePathDisplay")
        self.horizontalLayout_19.addWidget(self.influencePathDisplay)
        self.influencePathButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.influencePathButton.sizePolicy().hasHeightForWidth())
        self.influencePathButton.setSizePolicy(sizePolicy)
        self.influencePathButton.setMinimumSize(QtCore.QSize(28, 0))
        self.influencePathButton.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.influencePathButton.setFont(font)
        self.influencePathButton.setObjectName("influencePathButton")
        self.horizontalLayout_19.addWidget(self.influencePathButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_9.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_21.addWidget(self.label_9)
        self.configFileDisplay = QtWidgets.QLineEdit(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configFileDisplay.sizePolicy().hasHeightForWidth())
        self.configFileDisplay.setSizePolicy(sizePolicy)
        self.configFileDisplay.setMinimumSize(QtCore.QSize(104, 0))
        self.configFileDisplay.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.configFileDisplay.setFont(font)
        self.configFileDisplay.setMouseTracking(True)
        self.configFileDisplay.setText("")
        self.configFileDisplay.setReadOnly(False)
        self.configFileDisplay.setObjectName("configFileDisplay")
        self.horizontalLayout_21.addWidget(self.configFileDisplay)
        self.configFileButton = QtWidgets.QPushButton(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configFileButton.sizePolicy().hasHeightForWidth())
        self.configFileButton.setSizePolicy(sizePolicy)
        self.configFileButton.setMinimumSize(QtCore.QSize(28, 0))
        self.configFileButton.setMaximumSize(QtCore.QSize(28, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.configFileButton.setFont(font)
        self.configFileButton.setObjectName("configFileButton")
        self.horizontalLayout_21.addWidget(self.configFileButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.verticalLayout_4.addWidget(self.pathGroupBox)
        self.verticalLayout_4.setStretch(0, 4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.createTab, "")
        self.manageTab = QtWidgets.QWidget()
        self.manageTab.setObjectName("manageTab")
        self.layoutWidget5 = QtWidgets.QWidget(self.manageTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(20, 10, 771, 401))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.exitedListWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.exitedListWidget.setGeometry(QtCore.QRect(10, 30, 361, 161))
        self.exitedListWidget.setObjectName("exitedListWidget")
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.createdListWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.createdListWidget.setGeometry(QtCore.QRect(10, 20, 361, 171))
        self.createdListWidget.setObjectName("createdListWidget")
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 1)
        self.horizontalLayout_20.addLayout(self.verticalLayout_8)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.runningListWidget = QtWidgets.QListWidget(self.groupBox)
        self.runningListWidget.setGeometry(QtCore.QRect(10, 30, 361, 361))
        self.runningListWidget.setObjectName("runningListWidget")
        self.horizontalLayout_20.addWidget(self.groupBox)
        self.refreshListWidgetsButton = QtWidgets.QPushButton(self.manageTab)
        self.refreshListWidgetsButton.setGeometry(QtCore.QRect(717, 416, 75, 25))
        self.refreshListWidgetsButton.setObjectName("refreshListWidgetsButton")
        self.tabWidget.addTab(self.manageTab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.promptBrowser = QtWidgets.QTextBrowser(self.tab)
        self.promptBrowser.setGeometry(QtCore.QRect(-1, -1, 821, 301))
        self.promptBrowser.setStyleSheet("")
        self.promptBrowser.setObjectName("promptBrowser")
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.detailBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.detailBrowser.setGeometry(QtCore.QRect(-1, -1, 821, 291))
        self.detailBrowser.setObjectName("detailBrowser")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.logBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.logBrowser.setGeometry(QtCore.QRect(-1, -1, 821, 291))
        self.logBrowser.setObjectName("logBrowser")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 11)

        self.retranslateUi(RobustarLauncher)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RobustarLauncher)

    def retranslateUi(self, RobustarLauncher):
        RobustarLauncher.setWindowTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Robustar Launcher", None, -1))
        self.loadProfileButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Load Profile", None, -1))
        self.saveProfileButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Save Profile", None, -1))
        self.startServerButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Start Server", None, -1))
        self.stopServerButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Stop Server", None, -1))
        self.deleteServerButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Delete Server", None, -1))
        self.dockerGroupBox.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Docker", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Docker Container Name", None, -1))
        self.nameInput.setText(QtWidgets.QApplication.translate("RobustarLauncher", "robustar", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Docker Image Version", None, -1))
        self.versionComboBox.setCurrentText(QtWidgets.QApplication.translate("RobustarLauncher", "cuda11.1-0.0.1-beta", None, -1))
        self.versionComboBox.setItemText(0, QtWidgets.QApplication.translate("RobustarLauncher", "cuda11.1-0.0.1-beta", None, -1))
        self.versionComboBox.setItemText(1, QtWidgets.QApplication.translate("RobustarLauncher", "cpu-0.0.1-beta", None, -1))
        self.portGroupBox.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Port", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Website Port", None, -1))
        self.websitePortInput.setText(QtWidgets.QApplication.translate("RobustarLauncher", "8000", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Backend Port", None, -1))
        self.backendPortInput.setText(QtWidgets.QApplication.translate("RobustarLauncher", "6848", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Tensorboard Port", None, -1))
        self.tensorboardPortInput.setText(QtWidgets.QApplication.translate("RobustarLauncher", "6006", None, -1))
        self.pathGroupBox.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Path", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Train Set Path", None, -1))
        self.trainPathButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "...", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Test Set Path", None, -1))
        self.testPathButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "...", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Check Point Path", None, -1))
        self.checkPointPathButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "...", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Influence Result Path", None, -1))
        self.influencePathButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "...", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Config File Path", None, -1))
        self.configFileButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.createTab), QtWidgets.QApplication.translate("RobustarLauncher", "Create", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Exited", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Created", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("RobustarLauncher", "Running", None, -1))
        self.refreshListWidgetsButton.setText(QtWidgets.QApplication.translate("RobustarLauncher", "Refresh", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manageTab), QtWidgets.QApplication.translate("RobustarLauncher", "Manage", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtWidgets.QApplication.translate("RobustarLauncher", "Prompts", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtWidgets.QApplication.translate("RobustarLauncher", "Details", None, -1))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtWidgets.QApplication.translate("RobustarLauncher", "Logs", None, -1))

